name: Bump trivy

on:
  workflow_dispatch:
    inputs:
      trivy_version:
        required: true
        type: string
        description: the Trivy version

run-name: Bump Trivy to v${{ inputs.trivy_version }}

jobs:
  bump-trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Trivy versions
        run: |
          current_trivy_version=$(cat .github/workflows/build.yaml | sed -rn 's/TRIVY_VERSION: ([0-9]+\.[0-9]+\.[0-9]+)/\1/p' | xargs)
          sed -ri "s/ghcr.io\/aquasecurity\/trivy:$current_trivy_version/ghcr.io\/aquasecurity\/trivy:${{ inputs.trivy_version }}/" Dockerfile
          sed -ri "s/TRIVY_VERSION: $current_trivy_version/TRIVY_VERSION: ${{ inputs.trivy_version }}/" .github/workflows/build.yaml
          find test/data -type f -name '*.test' \
            | xargs sed -ri \
            "s/\"version\": \"$current_trivy_version\"/\"version\": \"${{ inputs.trivy_version }}\"/"

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}
          title: "chore(deps): Update trivy to v${{ inputs.trivy_version }}"
          commit-message: "chore(deps): Update trivy to v${{ inputs.trivy_version }}"
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch-suffix: timestamp
          branch: bump-trivy
          delete-branch: true

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
